version: "3.9"
services:
    capstone_app:
        build: capstone/
        env_file:
            - .env
        ports:
            - 3306:3306
        expose:
            - 8080
        volumes:
            - /static:/static
        command: python manage.py collectstatic --noinput
        command: python manage.py makemigrations --noinput
        command: python manage.py migrate --fake
        command: gunicorn capstone.wsgi --bind 0.0.0.0:8080

    nginx:
        build: nginx/
        env_file:
            - .env
        ports:
            - 80:80
            - 443:443
        volumes: 
            - /etc/letsencrypt:/etc/letsencrypt
            - /etc/ssl:/etc/ssl
            - /static:/static
        depends_on:
            - capstone_app
    mariadb:
        image: mariadb
        env_file:
            - .env
        expose:
            - 3306
        volumes: 
            - /home/ubuntu/wgu_project/mariadb_backup/:/var/lib/mysql
            - /home/ubuntu/wgu_project:/opt/
        environment:
            - MYSQL_ROOT_PASSWORD=${db_password}
            - MYSQL_DATABASE=${capstone}
            - MYSQL_USER=${test_user}
            - MYSQL_PASSWORD=${db_password}

